import { createRoot } from 'react-dom/client'
import './styles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './App'
import { useState } from 'react';

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

export default function Root() {
  const [meshId, setmeshId] = useState('');
  return (
    <div style={{
      width: "100vw",
      height: "100vh",
      color: '#fff',
      touchAction: 'none',
    }}>
      <App meshId={meshId} setmeshId={setmeshId} />
      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: "none" }}>
        <a style={{ position: 'absolute', top: 40, left: 40, fontSize: '13px', pointerEvents: "auto" }} href="#" onClick={() => setmeshId(null)}>
          {meshId ? '< back' : 'double click to enter portal'}
        </a>
        <span>{meshId}</span>
      </div>
    </div>
  )
}

